services:
  client:
    build:
      context: client
      target: development  # Use the 'development' stage from Dockerfile.prod for development
    command: npm run dev
    env_file:
      - client/.env
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    command: fastapi dev --port 8080 --host 0.0.0.0 
    env_file:
      - .env
    environment:
      - FRONTEND_URL=http://client
    ports:
      - 8080:8080
    volumes:
      - ./server:/app/server

  