version: '3.8'

services:
  client:
    build:
      context: client
      target: development  # Use the 'development' stage from Dockerfile.prod for development
    command: npm run dev
    env_file:
      - client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    command: fastapi dev main.py
    env_file:
      - .env
    environment:
      - FRONTEND_URL=http://client:3000
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server

  